# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "@APP_NAME@"
  profiles:
    default: "dev"
  config:
    import: [ ]
  autoconfigure:
    exclude: [ ]
  aop:
    auto: true
    proxy-target-class: true
  main:
    web-application-type: servlet
    banner-mode: log
    allow-bean-definition-overriding: true
    allow-circular-references: false
    log-startup-info: true
    cloud-platform: none
    lazy-initialization: false
    register-shutdown-hook: true
    sources:
      - "classpath:/META-INF/spring/beans.xml"
      - "classpath:/META-INF/spring/security.xml"
  banner:
    location: "classpath:/META-INF/banner.txt"
    charset: "utf-8"
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  jmx:
    enabled: false
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: "1GB"
      max-request-size: "2GB"
  task:
    execution:
      thread-name-prefix: "common-task-"
      pool:
        core-size: 15
        max-size: 30
        keep-alive: 60s
        queue-capacity: 45
        allow-core-thread-timeout: true
  batch:
    job:
      enabled: off

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
    shutdown:
      access: none
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: simple
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    ssl:
      enabled: true
    process:
      enabled: true
    defaults:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"

# ----------------------------------------------------------------------------------------------------------------------
# Actuator - info
# ----------------------------------------------------------------------------------------------------------------------
info:
  authors:
    - name: "应卓"
      email: "yingzhor@gmail.com"

# ----------------------------------------------------------------------------------------------------------------------
# 本应用配置
# ----------------------------------------------------------------------------------------------------------------------
application: { }


# ----------------------------------------------------------------------------------------------------------------------
# Swagger配置
# ----------------------------------------------------------------------------------------------------------------------
springdoc:
  api-docs:
    enabled: true
    path: "/v3/api-docs"
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    display-request-duration: true
    display-operation-id: true
  packages-to-scan:
    - "io.github.yingzhuo.showcase.core"
