debug: false

# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/spring_batch_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true"
    username: "root"
    password: "root"

# ----------------------------------------------------------------------------------------------------------------------
# 日志配置
# ----------------------------------------------------------------------------------------------------------------------
logback:
  log-home: "/tmp"
  log-name: "skeleton"
  log-pattern: "[%d{yyyy-MM-dd HH:mm:ss.SSS}]%-5level %logger{72}[%L] - %msg%n"
