# ----------------------------------------------------------------------------------------------------------------------
# Version Catalogs
# https://docs.gradle.org/current/userguide/version_catalogs.html
# ----------------------------------------------------------------------------------------------------------------------
[versions]
[libraries]
[bundles]
[plugins]
